In [3]:
import numpy as np


 ## numpy array


In [14]:
benimListem = [20,30,40]

In [16]:
type( benimListem )

list

In [18]:
np.array(benimListem) 

array([20, 30, 40])

In [26]:
matrixListesi = [ [10,20,30],[20,30,40],[30,40,50]]

In [28]:
type(matrixListesi)

list

In [31]:
np.array(matrixListesi) # matrise çevirme komutu np.arr(dizi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange  kullanımı 

In [33]:
list(range(0,10)) #klasik range fonksiyonu 0 10 arası sayıları oluşturur

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [35]:
np.arange(0,10)# numpy dizisi oluşturur range ile aynı matıkta farklı formatta

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(0,10,2) # atlayarak yazdırıyor 

array([0, 2, 4, 6, 8])

## zeros 0 matrisi  --- ones 1 matrisi

In [38]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:
np.zeros((2,2))  # istenen ölçülerde matris olarak oluşturdu 

array([[0., 0.],
       [0., 0.]])

In [40]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [41]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

### linspace istenen aralıkta ve istenen veri adedinde eşit aralıkta sayılar oluşturma 

In [42]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [43]:
np.linspace(0,10,20)#0 ile 10 arasında 20 tane veri olsun aralıkları eşit olsun 

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## eye simetrik matris oluşturur

In [46]:
np.eye(6) #köşegenler 1 geri kalanlar 0

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## random 

In [5]:
np.random.randn(5) #rastgele değerler üretir nnumpy dizisi üretir

array([ 0.64152139, -0.6863867 ,  0.55262696, -0.16678657,  0.82609205])

In [6]:
np.random.randn(3,3)

array([[-0.7081322 ,  0.01911251,  0.64829142],
       [ 0.38595039,  0.89527559, -0.97034512],
       [-0.16044967, -1.63861499,  0.40549545]])

In [9]:

np.random.randint(1,10) # 1 10 arası bir değer döndürür son değeri alamaz (10) ilk değeri alabilir

5

In [11]:
np.random.randint(1,100,5) # 1 100 arası 5 tane değer üret 

array([44, 49, 27, 70, 49], dtype=int32)

In [17]:
numpyDizim=np.arange(30) #bir değere eşitleme

In [18]:
numpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [19]:
benimRandomDizim= np.random.randint(0,40,5) #değere eşitleme

In [20]:
benimRandomDizim

array([ 5,  5, 22, 39, 29], dtype=int32)